; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp01_1m

[env:d1_mini_lite]
platform = espressif8266
board = d1_mini_lite
framework = arduino
upload_speed = 921600
monitor_speed = 74880
lib_deps = 
	ottowinter/ESPAsyncWebServer-esphome@^1.2.7
	ayushsharma82/AsyncElegantOTA@^2.2.7

[env:esp01_1m]
platform = espressif8266
board = esp01_1m
; use options from here for loader to configure flash layout
; https://github.com/esp8266/Arduino/tree/master/tools/sdk/ld
; eagle.flash.1m.ld = 1MB flash, no SPIFFS
board_build.ldscript = eagle.flash.1m.ld
framework = arduino
upload_speed = 921600
monitor_speed = 74880
lib_deps = 
	ottowinter/ESPAsyncWebServer-esphome@^1.2.7
	ayushsharma82/AsyncElegantOTA@^2.2.7
